spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_dish_db
    username: postgres
    password: toavina
    driver-class-name: org.postgresql.Driver

1spring:
  application:
    name: TD5
